[package]
name = "norm"
version = "0.1.0"
edition = "2021"
authors = ["Riccardo Mazzarini <me@noib3.dev>"]

[features]
default = ["fzf-v1"]
fzf-v1 = []

# Private features.
tests = ["fzf-v1"]

[dependencies]

[[test]]
name = "fzf-v1"
path = "./tests/fzf_v1.rs"
required-features = ["tests"]
