format_code_in_doc_comments = true
format_strings = true
group_imports = "StdExternalCrate"
imports_layout = "HorizontalVertical"
match_block_trailing_comma = true
max_width = 79
unstable_features = true
use_field_init_shorthand = true
use_small_heuristics = "Max"
